image: python:3.7.2-alpine3.8

stages:

  - deploy


before_script:

   - pip install --upgrade pip

   - pip install twine

   - python setup.py sdist bdist_wheel


deploy_production:

  stage: deploy

  variables:

    TWINE_USERNAME: $PRODUCTION_USERNAME

    TWINE_PASSWORD: $PRODUCTION_PASSWORD

  script:

    - twine upload dist/*

  only:

    - tags
