image: python:3.6.10-buster

stages:

  - build
  - test
  - deploy

test_job:
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "./tests/"


before_script:

   - pip install --upgrade pip

   - pip install twine

   - python setup.py sdist bdist_wheel


deploy_production:

  stage: deploy

  variables:

    TWINE_USERNAME: $PRODUCTION_USERNAME

    TWINE_PASSWORD: $PRODUCTION_PASSWORD

  script:

    - twine upload dist/*

  only:

    - tags
